spring:
  datasource:
    # Use the Transaction Pooler Host from your dashboard
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Specify PostgreSQL Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Email configuration for local/dev testing
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  cors:
    # Allows React frontend to communicate with Backend
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
  razorpay:
    # Test credentials for local development
    api-key: ${RAZORPAY_KEY}
    api-secret: ${RAZORPAY_SECRET}
  stripe:
    # Test credential for local development
    secret-key: ${STRIPE_SECRET}

server:
  # Standard port for local backend testing
  port: 8080