spring:
  datasource:
    # Use the Supabase Transaction Pooler URL for better performance on Render
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # Updated for PostgreSQL

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    show-sql: ${JPA_SHOW_SQL:false}
    # Specify PostgreSQL dialect for Hibernate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  razorpay:
    api-key: ${RAZORPAY_KEY}
    api-secret: ${RAZORPAY_SECRET}
  stripe:
    secret-key: ${STRIPE_SECRET}

server:
  # Render automatically injects the PORT variable
  port: ${PORT:8080}