spring:
  datasource:
    # Use the Transaction Pooler Host from your dashboard
    url: ${DB_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/buybaazar}
    username: ${DB_USER:postgres.asubdlfyzveevikjmnmz}
    password: ${DB_PASSWORD:Sahil444Agroha}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Specify PostgreSQL Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Email configuration for local/dev testing
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:sahilsheo444@gmail.com}
    password: ${MAIL_PASS:sujm gufu hncq kchf}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  cors:
    # Allows React frontend to communicate with Backend
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
  razorpay:
    # Test credentials for local development
    api-key: ${RAZORPAY_KEY:rzp_test_SCojDSLmfqCbNU}
    api-secret: ${RAZORPAY_SECRET:hLegU1rovtOus6Qm4hdonAK7}
  stripe:
    # Test credential for local development
    secret-key: ${STRIPE_SECRET:sk_test_51SxlmJLvNTauDOqlOA8XNFH0Y18qoEeehMdEGHiMCMesw10lwt5xnfqiSpN6l2kIALN6GGkMpLt7qi2d09cPIJAi00kXKFudfR}

server:
  # Standard port for local backend testing
  port: 8080